export const INCOME_VARS = [
  { key: 'wage_income',                      label: 'Wages / Salary' },
  { key: 'selfemp_income',                   label: 'Self-Employment' },
  { key: 'nontax_invest_income',             label: 'Non-Taxable Investment' },
  { key: 'interest_income',                  label: 'Interest' },
  { key: 'dividends_income',                 label: 'Dividends' },
  { key: 'stocks_bonds_income',              label: 'Stocks & Bonds' },
  { key: 'rent_trust_loyalty_income',        label: 'Rent / Trust / Royalties' },
  { key: 'unemployment_workercomp_income',   label: "Unemployment / Worker's Comp" },
  { key: 'childsupport_alimony_income',      label: 'Child Support / Alimony' },
  { key: 'tanf_ssi_foodstamp_income',        label: 'TANF / SSI / Food Stamps' },
  { key: 'pension_annulity_income',          label: 'Pension / Annuity' },
  { key: 'other_income',                     label: 'Other Income' },
]

export const DEBT_VARS = [
  { key: 'creditcard_debt',        label: 'Credit Card' },
  { key: 'storecard_debt',         label: 'Store Card' },
  { key: 'chargecard_debt',        label: 'Charge Card' },
  { key: 'mortgage1_debt',         label: 'Mortgage (Primary)' },
  { key: 'mortgage2_debt',         label: 'Mortgage (2nd)' },
  { key: 'mortgage3_debt',         label: 'Mortgage (3rd)' },
  { key: 'property1_debt',         label: 'Property Debt (1)' },
  { key: 'property2_debt',         label: 'Property Debt (2)' },
  { key: 'other_property_debt',    label: 'Other Property Debt' },
  { key: 'creditline1_debt',       label: 'Credit Line (1)' },
  { key: 'creditline2_debt',       label: 'Credit Line (2)' },
  { key: 'creditline3_debt',       label: 'Credit Line (3)' },
  { key: 'home_improvement_debt',  label: 'Home Improvement Loan' },
  { key: 'car1_debt',              label: 'Car Loan (1)' },
  { key: 'car2_debt',              label: 'Car Loan (2)' },
  { key: 'car3_debt',              label: 'Car Loan (3)' },
  { key: 'car4_debt',              label: 'Car Loan (4)' },
  { key: 'othervehicle1_debt',     label: 'Other Vehicle Loan (1)' },
  { key: 'othervehicle2_debt',     label: 'Other Vehicle Loan (2)' },
  { key: 'education1_debt',        label: 'Student Loan (1)' },
  { key: 'education2_debt',        label: 'Student Loan (2)' },
  { key: 'education3_debt',        label: 'Student Loan (3)' },
  { key: 'education4_debt',        label: 'Student Loan (4)' },
  { key: 'education5_debt',        label: 'Student Loan (5)' },
  { key: 'education6_debt',        label: 'Student Loan (6)' },
  { key: 'misc_loan1',             label: 'Misc. Loan (1)' },
  { key: 'misc_loan2',             label: 'Misc. Loan (2)' },
  { key: 'misc_loan3',             label: 'Misc. Loan (3)' },
  { key: 'misc_loan4',             label: 'Misc. Loan (4)' },
  { key: 'misc_loan5',             label: 'Misc. Loan (5)' },
  { key: 'misc_loan6',             label: 'Misc. Loan (6)' },
]

export const ASSET_VARS = [
  { key: 'checking_worth',         label: 'Checking Account' },
  { key: 'savingsmma1_worth',      label: 'Savings / MMA (1)' },
  { key: 'savingsmma2_worth',      label: 'Savings / MMA (2)' },
  { key: 'savingsmma3_worth',      label: 'Savings / MMA (3)' },
  { key: 'cds_worth',              label: 'CDs' },
  { key: 'usgovt_worth',           label: 'U.S. Gov Securities' },
  { key: 'stocks_worth',           label: 'Stocks / ETFs' },
  { key: 'bonds_worth',            label: 'Bonds' },
  { key: 'rothira_worth',          label: 'Roth IRA' },
  { key: 'tradera_worth',          label: 'Traditional IRA' },
  { key: '401k_worth',             label: '401(k)' },
  { key: 'pension_worth',          label: 'Pension' },
  { key: 'crypto_worth',           label: 'Cryptocurrency' },
  { key: 'realestate1_worth',      label: 'Real Estate (1)' },
  { key: 'realestate2_worth',      label: 'Real Estate (2)' },
  { key: 'vehicle1_worth',         label: 'Vehicle (1)' },
  { key: 'vehicle2_worth',         label: 'Vehicle (2)' },
  { key: 'business_worth',         label: 'Business Equity' },
  { key: 'otherasset_worth',       label: 'Other Asset' },
]

export const GOAL_OPTIONS = [
  'Buy a home',
  'Pay off debt',
  'Build emergency fund',
  'Invest for retirement',
  'Fund a project or business',
  'Support my community',
  'Save for education',
  'Other',
]

export const MOCK_BANKS = [
  'Ally Bank', 'American Express', 'Bank of America', 'Capital One',
  'Chase', 'Citibank', 'Discover', 'Marcus by Goldman Sachs',
  'Navy Federal', 'PNC Bank', 'SoFi', 'TD Bank', 'US Bank', 'Wells Fargo',
]

export const STRUCTURE_LABELS = {
  accountType:        { hysa: 'High-Yield Savings (HYSA)', checking: 'Checking', brokerage: 'Brokerage' },
  payInFrequency:     { weekly: 'Weekly', biweekly: 'Bi-weekly', monthly: 'Monthly' },
  payoutStructure:    { rotating: 'Rotating (ROSCA)', voted: 'Voted allocation', proportional: 'Proportional draw' },
  amendmentThreshold: { majority: 'Simple majority (>50%)', two_thirds: 'Two-thirds (≥67%)', unanimous: 'Unanimous' },
  quorum:             { any: 'Any member may vote', two_thirds: '2/3 of members must vote', all: 'All members must vote' },
  dishonorableExit:   { withheld: 'Funds withheld', returned_no_interest: 'Returned, no interest', returned_with_interest: 'Returned with interest' },
  probationPeriod:    { none: 'None', '1_month': '1 month', '3_months': '3 months', '6_months': '6 months' },
  latePaymentPolicy:  { grace_7: '7-day grace period', immediate_penalty: 'Immediate penalty', removal_3_missed: 'Removal after 3 missed', voted: 'Member vote' },
  exitNoticePeriod:   { immediate: 'Immediate', '1_month': '1 month', '2_months': '2 months', '3_months': '3 months', '1_cycle': '1 full cycle' },
  memberAdmission:    { vote_required: 'Vote required', invite_no_vote: 'Invite (no vote)', any_member: 'Open admission' },
}
